name: Docker Image Build and Run

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: |
          docker build -t prqlite:latest .

      - name: Smoke test container
        run: |
          printf "exit\n" | docker run -i --rm prqlite:latest
